# Generated by Django 5.2.5 on 2025-10-07 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Названии бренда')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='URL бренда')),
            ],
            options={
                'verbose_name': 'Название бренда',
                'verbose_name_plural': 'Название брендов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Названии категории')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='URL товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('count', models.IntegerField(default=1, verbose_name='Количество в наличии')),
                ('available', models.BooleanField(default=True, verbose_name='Активный товар')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('image', models.ImageField(blank=True, default='images/default.jpg', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg'))], verbose_name='Изображение товара')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['available', '-count', 'name'],
                'indexes': [models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'), models.Index(fields=['brand', 'category'], name='shop_produc_brand_i_33f772_idx'), models.Index(fields=['price', 'count'], name='shop_produc_price_877fdd_idx')],
            },
        ),
    ]
