# Generated by Django 5.2.7 on 2025-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_shop_produc_brand_i_33f772_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-create'], name='shop_produc_create_cc27fc_idx'),
        ),
    ]
